name: examples

on: [push, pull_request]

jobs:
  minimal-example:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: ghcr.io/langchr86/docmake:latest
    steps:
      - uses: actions/checkout@v2

      - name: configure and build
        run: |
          mkdir build
          cmake -S . -B build -DDOCMAKE_ENABLE_MINIMAL_EXAMPLE=ON
          cmake --build build

  maximal-example:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: ghcr.io/langchr86/docmake:latest
    env:
      DISPLAY: ":99"
    steps:
      - uses: actions/checkout@v2

      - name: "start xvfb as a workaround for drawio-desktop does not work without an X server"
        run: Xvfb :99 &

      - name: configure and build
        run: |
          mkdir build
          cmake -S . -B build -DDOCMAKE_ENABLE_MAXIMAL_EXAMPLE=ON
          cmake --build build
